feat: nginx gunicorn prod
mpdocs/mpdocs-backend pull request #10
Opened 2024-05-12 16:33 UTC by Screxy

добавил nginx
также добавил скрипт для прода с поднятием сервера через gunicorn

2024-05-18 08:53 UTC, Yakser requested changes

2024-05-18 08:53 UTC, yakser commented on service/settings.py
> +if DEBUG is True:
Можнр просто if debug

2024-05-18 08:53 UTC, Yakser commented on .gitignore
> -report_templates/
за шо

2024-05-18 08:53 UTC, Yakser commented on scripts/startup.sh
> +poetry run gunicorn service.wsgi:application --bind 0.0.0.0:8000
давай укажем 4 воркера например

2024-05-18 15:33 UTC, Screxy commented on .gitignore
> -report_templates/
быканул, согл

2024-05-18 15:33 UTC, Screxy commented on service/settings.py
> +if DEBUG is True:
ладно

2024-05-18 15:40 UTC, Screxy commented on .gitignore
> -report_templates/
это бага какая-то, я это не трогал, если файл посмотреть, эта строчка там есть

2024-05-20 09:02 UTC, Yakser requested changes

2024-05-20 09:02 UTC, yakser commented on .gitignore
> -report_templates/
ты прост строчку добваил новую и он подумал что ты старую удалил)

2024-05-20 09:02 UTC, Yakser commented on service/settings.py
>  ALLOWED_HOSTS: list[str] = []
а почему тут пусто?

2024-06-02 08:53 UTC, Screxy commented on service/settings.py
>  ALLOWED_HOSTS: list[str] = []
popravil s mastera

2024-06-02 09:11 UTC, Yakser approved these changes

2024-06-02 09:12 UTC, merged