feat: celery, redis
mpdocs/mpdocs-backend pull request #11
Opened 2024-05-15 21:14 UTC by Yakser

2024-05-15 21:16 UTC, Yakser commented on periodics/tasks.py
> +def debug_task():
позже удалим, оставил чтобы могли запустить и убедиться что все ок работает

2024-05-15 21:34 UTC, Screxy requested changes

2024-05-15 21:34 UTC, Screxy commented on Dockerfile
> +FROM python:3.12
в итоге не алпайн будем использовать чтоли

2024-05-15 21:34 UTC, Screxy commented on README.md
> +celery -A learnify worker -l INFO`or via `celery -A learnify worker -l INFO
какой еще лернифай

2024-05-15 21:34 UTC, Screxy commented on docker-compose.yaml
правки сюда вщ зачем, нам бы сначала с девом разобраться. + нету контейнера с бд

2024-05-15 21:34 UTC, Screxy commented on docker-compose.yaml
> +      dockerfile: Dockerfile.dev
дев?

2024-05-15 21:34 UTC, Screxy commented on service/settings.py
> +        "LOCATION": "redis://localhost:6379",
вщ конечно лучше это из окружения брать, а не хардкодить

2024-05-15 21:34 UTC, Screxy commented on service/settings.py
> +ASGI_APPLICATION = "learnify.asgi.application"
почему лернифай

2024-05-15 21:34 UTC, Screxy commented on docker-compose.dev.yaml
> +    build: .
вообще лучше бы сюда образ с тегом подставить, а не вот так.
а еще лучше вот так более явно
```
    build:
      context: ./
      dockerfile: Dockerfile.dev
```

2024-05-15 21:34 UTC, Screxy commented on docker-compose.dev.yaml
> +    build: .
тоже самое

2024-05-15 21:34 UTC, Screxy commented on docker-compose.dev.yaml
> +      - ./.env
здесь вроде просто можно  .env

2024-05-15 21:34 UTC, Screxy commented on docker-compose.dev.yaml
> +      - ./.env
здесь вроде просто можно .env

2024-05-15 21:35 UTC, Yakser commented on Dockerfile
> +FROM python:3.12
он не билдится у меня на маке)) с gcc проблемы

2024-05-15 21:36 UTC, Yakser commented on README.md
> +celery -A learnify worker -l INFO`or via `celery -A learnify worker -l INFO
пофикшу, с курсача копипастил

2024-05-15 21:36 UTC, Yakser commented on docker-compose.yaml
Контейнер с бд есть

2024-05-15 21:37 UTC, Yakser commented on docker-compose.yaml
> +      dockerfile: Dockerfile.dev
Пофикшу, чет хз откуда оно тут появилось. Тоже докопипастилсч

2024-05-15 21:37 UTC, Screxy commented on docker-compose.dev.yaml
> +    image: redis:7
я бы так сделал

```
  redis:
    image: redis:latest
    volumes:
      - чтонибудь:/root/redis
      - чтонибудь:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
```

2024-05-15 21:37 UTC, Yakser commented on service/settings.py
> +        "LOCATION": "redis://localhost:6379",
Согласен, еще в location локалхост указан, оно в докере отъебнет скорее всего

2024-05-15 21:37 UTC, Yakser commented on service/settings.py
> +ASGI_APPLICATION = "learnify.asgi.application"
Потому что это мой курсач м сейчас половина второго ночи🥲💀💀💀

2024-05-15 21:39 UTC, Yakser commented on docker-compose.dev.yaml
> +    build: .
Оке, поправлю. Но кст что это дает помимо явного указания докерфайла?

2024-05-15 22:03 UTC, Screxy commented on Dockerfile
> +FROM python:3.12
значит надо другую версию образа смотреть

2024-05-15 22:05 UTC, Screxy commented on service/settings.py
> +        "LOCATION": "redis://localhost:6379",
в докере просто redis

2024-05-15 22:05 UTC, Screxy commented on docker-compose.dev.yaml
> +    build: .
поидее ничего. ну читабельность

2024-05-15 22:07 UTC, Screxy commented on docker-compose.yaml
ну в данном мр в данном файле его не вижу

2024-05-18 15:42 UTC, yakser commented on docker-compose.dev.yaml
> +    image: redis:7
Интересно джанга тогда сможет подрубиться или нет, но думаю разберемся. Пока не крит как будто. Кстати зачем делать volume с редисом? Это ж in-memory хранилище. Или он на диск бэкапы делает по дефолту?

2024-05-18 15:42 UTC, yakser commented on docker-compose.yaml
Точнее сервис

2024-05-18 15:42 UTC, yakser commented on README.md
> +celery -A learnify worker -l INFO`or via `celery -A learnify worker -l INFO
Везде где леонифай надо заменитт на service, это просто имя проекта

2024-05-18 15:42 UTC, yakser commented on Dockerfile
> +FROM python:3.12
какую? чем плох просто питончик дефолтный
это сейчас критично?

2024-05-18 15:42 UTC, yakser commented on README.md
> +celery -A learnify worker -l INFO`or via `celery -A learnify worker -l INFO
поправил

2024-05-18 15:42 UTC, yakser commented on docker-compose.yaml
поправил

2024-05-18 15:42 UTC, yakser commented on docker-compose.yaml
> +      dockerfile: Dockerfile.dev
поправил

2024-05-18 15:42 UTC, yakser commented on service/settings.py
> +        "LOCATION": "redis://localhost:6379",
redis://redis:6379 будет
поправил

2024-05-18 15:42 UTC, yakser commented on service/settings.py
> +ASGI_APPLICATION = "learnify.asgi.application"
поправил

2024-05-18 15:42 UTC, yakser commented on docker-compose.dev.yaml
> +    build: .
Я вот тут хз как билдятся эти сервисы
по сути там даже билд не нужен, они просто зависят от сервиса backend и запускают 1 команду. имхо указание докерфайла тут только запутает сильнее, но я не знаю способа не билдить заново сервис. нужно поресерчить.

2024-05-18 15:42 UTC, yakser commented on docker-compose.dev.yaml
> +      - ./.env
done

2024-05-18 15:42 UTC, yakser commented on docker-compose.dev.yaml
> +      - ./.env
done

2024-05-18 15:43 UTC, Screxy commented on Dockerfile
> +FROM python:3.12
алпайн версии легче весит, для прода как будто бы да) но вообще пох по сути.

2024-05-18 15:45 UTC, Screxy commented on docker-compose.dev.yaml
> +    build: .
я могу сделать это позже, билдить образ с тегом и подставлять сюда название образ а не файл для билда

2024-05-18 15:45 UTC, Screxy commented on docker-compose.dev.yaml
> +    image: redis:7
на диск да записывает, его же можно как просто бд юзать

2024-05-18 15:48 UTC, Screxy requested changes

2024-05-18 15:48 UTC, Screxy commented on README.md
> +celery -A service worker -l INFO`or via `celery -A learnify worker -l INFO
learnify

2024-05-18 16:34 UTC, Screxy commented on docker-compose.dev.yaml
> +    build: .
создал мр, где в докеркомпозе вставляется имя образа, соответвенно в других места также должно быть
https://github.com/mpdocs/mpdocs-backend/pull/12

2024-05-18 19:44 UTC, Yakser commented on Dockerfile
> +FROM python:3.12
давай займемся этим когда не будет других горящих задач

2024-05-18 19:47 UTC, Screxy approved these changes

2024-05-18 19:48 UTC, merged

2024-05-18 19:48 UTC, Screxy commented on Dockerfile
> +FROM python:3.12
ну вообще доеб был из-за того, что ты вообще начал трогать продовые файлы) я так и предпологал делать)