Image tag ghcr.io
mpdocs/mpdocs-backend pull request #12
Opened 2024-05-18 16:33 UTC by Screxy

поправил команду в makefile для билда образа бека, теперь проставляется тег и в докеркомпозах соответсвенно используется + добавил команду для продовской сборки

2024-05-18 19:50 UTC, Yakser commented on docker-compose.dev.yaml
> +    image: ghcr.io/mpdocs/backend:dev
а как оно работает

2024-05-18 19:53 UTC, Yakser requested changes

2024-05-18 19:53 UTC, Yakser commented on docker-compose.dev.yaml
> +    image: ghcr.io/mpdocs/backend:dev
продовый композ не надо также поправить?

2024-05-18 19:56 UTC, Yakser requested changes

2024-05-18 19:56 UTC, Yakser commented on Makefile
> +	docker build --platform=linux/amd64 -f ./Dockerfile.dev . -t ${REGISTRY}/backend:prod
dev dockerfile вместо продового

2024-06-02 08:09 UTC, Yakser commented on Makefile
> +	docker build -f ./Dockerfile.dev . -t ${REGISTRY}/backend:dev
зачем для дева реджистри указывать?

2024-06-02 08:11 UTC, Screxy commented on Makefile
> +	docker build -f ./Dockerfile.dev . -t ${REGISTRY}/backend:dev
чтобы дать понятный тег для образа и в случае чего можно пушнуть в реджистри.

2024-06-02 08:12 UTC, Screxy commented on docker-compose.dev.yaml
> +    image: ghcr.io/mpdocs/backend:dev
мы же решили, продовые файлы потом, как разберемся

2024-06-02 08:16 UTC, Yakser approved these changes

2024-06-02 08:16 UTC, merged