генерация статистики на основе отчетов
mpdocs/mpdocs-backend pull request #15
Opened 2024-07-01 19:39 UTC by Screxy

- данные берутся из отчетов
- много данных, которых нет в отчетах, мб придется делать фронт под это
- нужно ли хранить данные об сгенерированных отчетах?

2024-07-01 21:02 UTC, Yakser requested changes

2024-07-01 21:02 UTC, Yakser commented on Makefile
> +connect:
гениально

2024-07-01 21:02 UTC, Yakser commented on reports/models.py
> +# надо ли хранить их?
нет, зачем?

2024-07-01 21:05 UTC, Yakser requested changes

2024-07-01 21:05 UTC, Yakser commented on reports/models.py
> +    # пока не уверен, нужно ли оно будет
пусть будет

2024-07-01 21:05 UTC, Yakser commented on reports/models.py
> +        on_delete=models.SET_NULL,  # хотим хранить отчёт, даже если кто-то удалил темплейт
хорошее решение

2024-07-01 21:05 UTC, Yakser commented on reports/models.py
> +        null=True,  # сомнительно
это пиздец как сомнительно, надо not null

2024-07-01 21:05 UTC, Yakser commented on reports/models.py
> +        # хотим хранить отчёты, даже если пользователь удалён
очепятка мб, про какого пользователя тут речь

2024-07-01 21:05 UTC, Yakser commented on reports/models.py
> +        return f"Данные по статистике {self.name}"
добавь еще `__repr__` f"Stats(id=..., name=...)"

2024-07-01 21:05 UTC, Yakser commented on reports/serializers.py
> +# class StatsSerializer(serializers.Serializer):
?

2024-07-01 21:05 UTC, Yakser commented on reports/urls.py
> +    path("stats/generate/", StatsGenerateView.as_view(), name="stats_generate", )
у нас тут даже скорее не статистика а аггрегация

2024-07-01 21:05 UTC, Yakser commented on reports/urls.py
> +    path("stats/generate/", StatsGenerateView.as_view(), name="stats_generate", )
хотя пох и так норм, но мб все таки statistics?)

2024-07-01 21:07 UTC, yakser requested changes

2024-07-01 21:07 UTC, yakser commented on reports/views.py
> +            for web_of_science_article in data["web_of_science_articles"]:
почему нельзя завести массив ключей и проходиться по нему?

2024-07-01 21:10 UTC, Yakser requested changes

2024-07-01 21:10 UTC, Yakser commented on reports/views.py
> +                "name": user.first_name + " " + user.last_name + " " + user.patronymic,
ай-ай-ай
f-строку давай заюзаем, это тебе не жс чтобы тут строки складывать

2024-07-01 21:10 UTC, Yakser commented on reports/views.py
> +                "title_count": len(data["web_of_science_articles"]) + len(data["scopus_articles"])
title?

2024-07-01 21:10 UTC, Yakser commented on reports/views.py
> +                "title_count": len(data["web_of_science_articles"]) + len(data["scopus_articles"])
не артиклс?

2024-07-01 21:13 UTC, Yakser requested changes

2024-07-01 21:13 UTC, yakser commented on reports/views.py
> +            f"{stats_template.name}-{datetime.datetime.now()}.docx"
nit: давай тут заюзем isoformat и сделаем реплейс миллисекунд на 0

2024-07-01 21:13 UTC, yakser commented on reports/views.py
> +            f"{stats_template.name}-{datetime.datetime.now()}.docx"
это больше так, доебка. не крит

2024-07-01 21:18 UTC, Screxy commented on Makefile
> +connect:
спасибо

2024-07-01 21:19 UTC, Screxy commented on reports/models.py
> +        null=True,  # сомнительно
убрал

2024-07-01 21:19 UTC, Screxy commented on reports/models.py
> +        # хотим хранить отчёты, даже если пользователь удалён
убрал

2024-07-01 21:19 UTC, Screxy commented on reports/models.py
> +        return f"Данные по статистике {self.name}"
убрал

2024-07-01 21:19 UTC, Screxy commented on reports/models.py
> +# надо ли хранить их?
убрал

2024-07-01 21:20 UTC, Screxy commented on reports/serializers.py
> +# class StatsSerializer(serializers.Serializer):
убрал

2024-07-01 21:20 UTC, Screxy commented on reports/urls.py
> +    path("stats/generate/", StatsGenerateView.as_view(), name="stats_generate", )
> хотя пох и так норм, но мб все таки statistics?)

не, писать меньше)))

2024-07-01 21:30 UTC, Screxy commented on reports/views.py
> +                "name": user.first_name + " " + user.last_name + " " + user.patronymic,
поправил

2024-07-01 21:32 UTC, Screxy commented on reports/views.py
> +                "title_count": len(data["web_of_science_articles"]) + len(data["scopus_articles"])
поправил

2024-07-01 21:32 UTC, Screxy commented on reports/views.py
> +            f"{stats_template.name}-{datetime.datetime.now()}.docx"
сделал

2024-07-02 19:18 UTC, Yakser requested changes

2024-07-02 19:18 UTC, Yakser commented on reports/views.py
> +            # Проходим по каждой категории данных и добавляем их в соответствующие списки
лишний коммент имхо

2024-07-02 19:18 UTC, Yakser commented on reports/views.py
> +        employees = []
отписал в тг тебе

2024-07-02 19:34 UTC, Screxy commented on reports/views.py
> +            # Проходим по каждой категории данных и добавляем их в соответствующие списки
удалил

2024-07-02 19:34 UTC, Screxy commented on reports/views.py
> +        employees = []
поправил

2024-07-02 20:10 UTC, Yakser approved these changes

2024-07-02 20:10 UTC, merged